apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bot-server
  namespace: saracinema
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`cinema.sara.watch`)
    kind: Rule
    middlewares:
      - name: headers-default@file
    services:
    - name: bot-server
      namespace: saracinema
      port: 80
  tls:
    certResolver: letsencrypt