apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-server
  namespace: saracinema
spec:
  template:
    spec:
      containers:
        - name: bot-server
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: app-config
              mountPath: "/app-config"
              readOnly: true
      volumes:
        - name: app-config
          secret:
            secretName: saracinema-env