apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml

secretGenerator:
  - files:
      - .env
    name: saracinema-env
    namespace: saracinema
    type: Opaque